options:
  key:
    type: string
    default: "1234567989ABCDEF"
    description: |
        The version of Kubernetes to use in this charm.  The version is
        inserted in the configuration files that specify the hyperkube
        container to use when starting a Kubernetes cluster.  Changing this
        value will restart the Kubernetes cluster.
